(()=>{
const $=id=>document.getElementById(id);
function addStyle(){const s=document.createElement('style');s.textContent=`
.side button svg{width:31px;height:31px;stroke:currentColor;fill:none;stroke-width:2}
.side button:nth-child(8){background:linear-gradient(180deg,#4e8cff,#3569df)}
.pg-toast{position:fixed;left:50%;bottom:26px;transform:translateX(-50%) translateY(20px);background:#123d82;color:#fff;padding:12px 18px;border-radius:14px;font-weight:900;opacity:0;transition:.2s;z-index:999;pointer-events:none}.pg-toast.show{opacity:1;transform:translateX(-50%) translateY(0)}
.pg-form{display:grid;grid-template-columns:1fr 1fr auto;gap:10px;align-items:end}.pg-form input,.pg-form select,.pg-form textarea,.settings-grid input{width:100%;padding:10px;border:1px solid var(--line);border-radius:10px;background:var(--card);color:var(--ink)}
.pg-list{display:grid;gap:10px;margin-top:14px}.pg-item{display:flex;justify-content:space-between;gap:12px;padding:12px;border:1px solid var(--line);border-radius:14px;background:var(--card)}.pg-item small{color:var(--muted)}.pg-mini{display:flex;gap:6px;flex-wrap:wrap}.pg-mini button{border:1px solid var(--line);border-radius:9px;padding:7px 9px;background:var(--card);color:var(--ink)}
.pg-search{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-bottom:12px}.pg-search input,.pg-search select{width:100%;padding:10px;border:1px solid var(--line);border-radius:10px;background:var(--card);color:var(--ink)}
.topbox.pg-editable{cursor:pointer}
@media(max-width:760px){.pg-form,.pg-search{grid-template-columns:1fr}}
`;document.head.appendChild(s)}
function toast(msg){let t=$('pgToast');if(!t){t=document.createElement('div');t.id='pgToast';t.className='pg-toast';document.body.appendChild(t)}t.textContent=msg;t.classList.add('show');clearTimeout(window.pgToastTimer);window.pgToastTimer=setTimeout(()=>t.classList.remove('show'),1800)}
const icons=[
`<svg viewBox="0 0 24 24"><path d="M3 11 12 4l9 7v9H3z"/><path d="M9 20v-6h6v6"/></svg>`,
`<svg viewBox="0 0 24 24"><rect x="5" y="4" width="14" height="17" rx="2"/><path d="M8 2v4M16 2v4M8 10h8M8 14h8"/></svg>`,
`<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="9"/><path d="M12 7v10M7 12h10"/></svg>`,
`<svg viewBox="0 0 24 24"><circle cx="8" cy="9" r="3"/><circle cx="16" cy="9" r="3"/><path d="M3 20c0-4 2-6 5-6s5 2 5 6M11 20c0-4 2-6 5-6s5 2 5 6"/></svg>`,
`<svg viewBox="0 0 24 24"><path d="M4 20h16M6 20l3-8h6l3 8M9 12V5h6v7"/></svg>`,
`<svg viewBox="0 0 24 24"><path d="M8 5h8M6 9h12M5 13h14M7 17h10"/><circle cx="4" cy="9" r="1"/><circle cx="20" cy="13" r="1"/></svg>`,
`<svg viewBox="0 0 24 24"><rect x="4" y="3" width="16" height="18" rx="2"/><path d="m8 10 2 2 4-4M8 16h8"/></svg>`,
`<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="3"/><path d="M19 12a7 7 0 0 0-.1-1l2-1.5-2-3.5-2.4 1A7 7 0 0 0 15 6l-.3-2.6h-4L10.4 6A7 7 0 0 0 8.5 7l-2.4-1-2 3.5L6.1 11A7 7 0 0 0 6 12c0 .3 0 .7.1 1l-2 1.5 2 3.5 2.4-1A7 7 0 0 0 10 18l.4 2.6h4L15 18a7 7 0 0 0 1.5-1l2.4 1 2-3.5-2-1.5c.1-.3.1-.7.1-1z"/></svg>`];
const baseActivities=[
['La mancha congelada','Persecución','Quien es tocado queda congelado hasta que un compañero lo libera.'],['Colores','Persecución','El perseguidor nombra un color y todos buscan tocar algo de ese color.'],['Cazadores y conejos','Persecución','Los cazadores intentan tocar a los conejos, cambiando roles.'],['El lobo y las ovejas','Roles y simbólicos','Un niño representa al lobo y los demás cruzan el espacio como ovejas.'],['Viaje a la selva','Roles y simbólicos','Moverse imitando animales y resolviendo consignas del entorno imaginario.'],['Superhéroes','Roles y simbólicos','Desplazarse representando poderes y acciones elegidas por el grupo.'],['Islas cooperativas','Cooperativos','Todo el grupo debe ubicarse en cada vez menos aros sin dejar a nadie afuera.'],['Transportar el tesoro','Cooperativos','Trasladar objetos entre todos sin que caigan y acordando estrategias.'],['El espejo','Conciencia corporal','Por parejas, uno realiza movimientos y el otro los reproduce.'],['Partes del cuerpo','Conciencia corporal','Responder a consignas movilizando distintas partes del cuerpo.'],['Dentro y fuera','Orientación espacial','Moverse y ubicarse dentro, fuera, cerca o lejos según la señal.'],['Caminos y puentes','Orientación espacial','Recorrer trayectos con cambios de dirección, altura y nivel.'],['Pelota viajera','Manipulación','Pasar una pelota de diferentes maneras alrededor del grupo.'],['Lanza y atrapa','Manipulación','Lanzar y recibir variando altura, distancia y objeto.'],['Estatuas','Equilibrio y gimnasia','Desplazarse y detenerse en posiciones de equilibrio a la señal.'],['Circuito de saltos','Equilibrio y gimnasia','Superar estaciones con saltos, apoyos y equilibrios.'],['Semáforo musical','Expresión y ritmo','Moverse según la música y cambiar la acción ante señales.'],['Estatuas musicales','Expresión y ritmo','Bailar y congelar una postura cuando se detiene la música.'],['Pases por puertas','Deporte','Pasar una pelota entre conos buscando precisión.'],['Mini partido adaptado','Deporte','Juego reducido con pocas reglas y consignas acordes a la edad.'],['Relevos variados','Atletismo','Carreras por equipos con diferentes formas de salida y desplazamiento.'],['Reacción a señales','Atletismo','Salir o cambiar dirección ante señales visuales o sonoras.'],['Respirar y estirar','Vuelta a la calma','Respiración guiada y movimientos suaves de estiramiento.'],['La nube','Vuelta a la calma','Relajación breve imaginando que el cuerpo se vuelve liviano.']];
function getActivities(){return baseActivities.map((x,i)=>({id:'b'+i,name:x[0],category:x[1],desc:x[2],base:true})).concat(JSON.parse(localStorage.getItem('profego-activities')||'[]'))}
function patchNav(){const nav=document.querySelector('.side');if(!nav)return;let btns=[...nav.querySelectorAll('button')];if(!btns.some(b=>b.textContent.includes('Actividades'))){const act=document.createElement('button');act.setAttribute('onclick',"show('activities',this)");act.innerHTML='<span>Actividades</span>';nav.insertBefore(act,btns[5]);btns=[...nav.querySelectorAll('button')]}btns.forEach((b,i)=>{const label=b.querySelector('span')?.textContent||'';if(i<icons.length)b.innerHTML=icons[i]+`<span>${label}</span>`})}
function patchTop(){const boxes=[...document.querySelectorAll('.topbox')];const inst=boxes.find(x=>x.textContent.includes('Institución'));if(inst){inst.classList.add('pg-editable');inst.onclick=editInstitution;let b=inst.querySelector('b');if(b)b.id='institutionTop'}const hero=document.querySelector('.hero h2');if(hero)hero.id='helloTitle'}
function patchPages(){const main=document.querySelector('main.main');if(!main)return;let res=$('resources');if(res)res.innerHTML=`<h2>Recursos</h2><div class="card"><h3>Agregar material</h3><div class="pg-form"><div><label>Recurso</label><input id="resourceName" placeholder="Ej.: pelotas"></div><div><label>Cantidad</label><input id="resourceQty" type="number" min="1" value="1"></div><button class="save" onclick="addResource()">Agregar</button></div><div id="resourceList" class="pg-list"></div></div>`;if(!$('activities')){const sec=document.createElement('section');sec.id='activities';sec.className='page';sec.innerHTML=`<h2>Actividades</h2><div class="card"><h3>Banco de juegos</h3><div class="pg-search"><input id="activitySearch" placeholder="Buscar juego..." oninput="renderActivities()"><select id="activityFilter" onchange="renderActivities()"><option value="">Todas las categorías</option>${['Persecución','Roles y simbólicos','Cooperativos','Conciencia corporal','Orientación espacial','Manipulación','Equilibrio y gimnasia','Expresión y ritmo','Deporte','Atletismo','Vuelta a la calma'].map(x=>`<option>${x}</option>`).join('')}</select></div><div class="pg-form"><div><label>Nombre</label><input id="activityName" placeholder="Nombre del juego"></div><div><label>Categoría</label><select id="activityCategory">${['Persecución','Roles y simbólicos','Cooperativos','Conciencia corporal','Orientación espacial','Manipulación','Equilibrio y gimnasia','Expresión y ritmo','Deporte','Atletismo','Vuelta a la calma'].map(x=>`<option>${x}</option>`).join('')}</select></div><button class="save" onclick="addActivity()">Agregar</button></div><textarea id="activityDesc" rows="2" placeholder="Descripción breve" style="width:100%;margin-top:10px;padding:10px;border:1px solid var(--line);border-radius:10px;background:var(--card);color:var(--ink)"></textarea><div id="activityList" class="pg-list"></div></div>`;main.insertBefore(sec,$('eval'))}const settings=$('settings');if(settings){settings.innerHTML=`<h2>Ajustes</h2><div class="settings-grid"><div class="card"><h3>Perfil</h3><label>Nombre</label><input id="profileName" placeholder="Profe"><label style="display:block;margin-top:10px">Institución</label><input id="institutionInput" placeholder="Mi institución"><button class="save" style="margin-top:12px" onclick="saveProfile()">Guardar perfil</button></div><div class="card"><h3>País</h3><select id="country" onchange="setCountry(this.value)"><option>Uruguay</option><option>Argentina</option><option>Brasil</option><option>Chile</option><option>Paraguay</option><option>Otro</option></select></div><div class="card"><h3>Apariencia</h3><p>Usá la luna o el sol de arriba para cambiar el modo.</p></div></div>`}}
function relevant(c){const t=c.toLowerCase(),all=getActivities();let cats=[];if(t.includes('juego'))cats=['Persecución','Roles y simbólicos','Cooperativos'];else if(t.includes('conciencia'))cats=['Conciencia corporal','Orientación espacial'];else if(t.includes('gimnas'))cats=['Equilibrio y gimnasia'];else if(t.includes('expres'))cats=['Expresión y ritmo'];else if(t.includes('deporte'))cats=['Deporte','Manipulación'];const p=cats.length?all.filter(a=>cats.includes(a.category)):all;return p.length?p:all}
function card(a,i,lesson){return `<article class="game"><h4>${i+1} · ${a.name}</h4><div class="scene"></div><p>${a.desc}</p><div class="actions"><button onclick="suggest(this)">↻ Sugerir otro</button><button class="edit" onclick="chooseActivity(this)">＋ Actividades</button></div></article>`}
window.generate=function(){try{const g=$('group'),c=$('content'),n=$('count'),goal=$('goal'),classes=$('classes'),meta=$('meta'),side=$('sideGoal');if(!g||!c||!n||!classes){toast('No pude abrir el generador');return}const idx=Number(c.value||0),data=window.curriculum?.[g.value]?.[idx]||curriculum?.[g.value]?.[idx];if(!data){toast('Elegí un contenido válido');return}const pool=relevant(data[0]);let html='';for(let lesson=1;lesson<=Number(n.value);lesson++){const stage=lesson===1?'Exploración inicial':lesson===Number(n.value)?'Cierre y aplicación':lesson<=Math.ceil(Number(n.value)/3)?'Exploración':lesson<=Math.ceil(Number(n.value)*2/3)?'Desarrollo':'Aplicación';const chosen=[];for(let i=0;i<6;i++)chosen.push(pool[(i+lesson-1)%pool.length]);html+=`<div class="classbox"><div class="class-title">CLASE ${lesson} · ${stage} · ${g.value}</div><div class="games">${chosen.map((a,i)=>card(a,i,lesson)).join('')}</div></div>`}classes.innerHTML=html;if(meta)meta.textContent=n.value+' clases';if(side)side.textContent=goal?.value||data[1];toast('✓ Planificación generada');setTimeout(()=>document.querySelectorAll('.scene').forEach((s,i)=>s.dispatchEvent(new Event('pgscene'))),30)}catch(e){console.error(e);toast('No se pudo generar la planificación')}};
window.savePlan=function(){try{const g=$('group'),c=$('content'),goal=$('goal'),n=$('count'),classes=$('classes');if(!g||!c||!classes||!classes.innerHTML.trim()){toast('Primero generá la planificación');return}const idx=Number(c.value||0),data=curriculum[g.value]?.[idx];const arr=JSON.parse(localStorage.getItem('profego-plans')||'[]');arr.unshift({id:Date.now(),group:g.value,content:data?.[0]||c.options[c.selectedIndex]?.text,goal:goal?.value||'',count:n?.value||'',country:localStorage.getItem('profego-country')||'Uruguay',html:classes.innerHTML});localStorage.setItem('profego-plans',JSON.stringify(arr));if(window.renderPlans)renderPlans();toast('✓ Planificación guardada')}catch(e){console.error(e);toast('No se pudo guardar')}};
window.suggest=function(btn){const a=getActivities()[Math.floor(Math.random()*getActivities().length)],g=btn.closest('.game');g.querySelector('h4').textContent=g.querySelector('h4').textContent.split('·')[0]+'· '+a.name;g.querySelector('p').textContent=a.desc};
window.chooseActivity=function(btn){const q=(prompt('Buscar por nombre o categoría:','')||'').toLowerCase(),m=getActivities().filter(a=>!q||a.name.toLowerCase().includes(q)||a.category.toLowerCase().includes(q));if(!m.length){toast('No encontré actividades');return}const txt=m.slice(0,8).map((a,i)=>`${i+1}. ${a.name} (${a.category})`).join('\n'),pick=Number(prompt('Elegí un número:\n'+txt,'1'))||1,a=m[pick-1];if(!a)return;const g=btn.closest('.game');g.querySelector('h4').textContent=g.querySelector('h4').textContent.split('·')[0]+'· '+a.name;g.querySelector('p').textContent=a.desc;toast('Actividad reemplazada')};
window.addResource=function(){const name=$('resourceName')?.value.trim(),qty=Number($('resourceQty')?.value)||1;if(!name){toast('Escribí un recurso');return}const a=JSON.parse(localStorage.getItem('profego-resources')||'[]');a.push({id:Date.now(),name,qty});localStorage.setItem('profego-resources',JSON.stringify(a));$('resourceName').value='';renderResources();toast('Recurso agregado')};
window.renderResources=function(){const el=$('resourceList');if(!el)return;const a=JSON.parse(localStorage.getItem('profego-resources')||'[]');el.innerHTML=a.length?a.map(r=>`<div class="pg-item"><div><b>${r.name}</b><br><small>Cantidad: ${r.qty}</small></div><div class="pg-mini"><button onclick="editResource(${r.id})">Editar</button><button onclick="deleteResource(${r.id})">Eliminar</button></div></div>`).join(''):'<div class="empty">Agregá los materiales que tenés disponibles.</div>'};
window.editResource=function(id){const a=JSON.parse(localStorage.getItem('profego-resources')||'[]'),r=a.find(x=>x.id===id);if(!r)return;const name=prompt('Recurso:',r.name),qty=prompt('Cantidad:',r.qty);if(name){r.name=name;r.qty=Number(qty)||r.qty;localStorage.setItem('profego-resources',JSON.stringify(a));renderResources();toast('Recurso actualizado')}};
window.deleteResource=function(id){const a=JSON.parse(localStorage.getItem('profego-resources')||'[]').filter(x=>x.id!==id);localStorage.setItem('profego-resources',JSON.stringify(a));renderResources();toast('Recurso eliminado')};
window.addActivity=function(){const name=$('activityName')?.value.trim(),category=$('activityCategory')?.value,desc=$('activityDesc')?.value.trim();if(!name){toast('Escribí el nombre del juego');return}const a=JSON.parse(localStorage.getItem('profego-activities')||'[]');a.push({id:Date.now(),name,category,desc:desc||'Actividad creada por el docente.',base:false});localStorage.setItem('profego-activities',JSON.stringify(a));$('activityName').value='';$('activityDesc').value='';renderActivities();toast('Actividad agregada')};
window.renderActivities=function(){const el=$('activityList');if(!el)return;const q=($('activitySearch')?.value||'').toLowerCase(),cat=$('activityFilter')?.value||'',a=getActivities().filter(x=>(!q||x.name.toLowerCase().includes(q)||x.desc.toLowerCase().includes(q))&&(!cat||x.category===cat));el.innerHTML=a.map(x=>`<div class="pg-item"><div><b>${x.name}</b><br><small>${x.category}</small><p style="margin:6px 0 0;color:var(--muted);font-size:12px">${x.desc}</p></div>${x.base?'':`<div class="pg-mini"><button onclick="deleteActivity(${x.id})">Eliminar</button></div>`}</div>`).join('')};
window.deleteActivity=function(id){localStorage.setItem('profego-activities',JSON.stringify(JSON.parse(localStorage.getItem('profego-activities')||'[]').filter(x=>x.id!==id)));renderActivities();toast('Actividad eliminada')};
window.saveProfile=function(){const name=$('profileName')?.value.trim()||'Profe',inst=$('institutionInput')?.value.trim()||'Mi institución';localStorage.setItem('profego-name',name);localStorage.setItem('profego-institution',inst);applyProfile();toast('✓ Perfil guardado')};
window.applyProfile=function(){const name=localStorage.getItem('profego-name')||'Profe',inst=localStorage.getItem('profego-institution')||'Mi institución';if($('profileName'))$('profileName').value=name;if($('institutionInput'))$('institutionInput').value=inst;if($('institutionTop'))$('institutionTop').textContent=inst;if($('helloTitle'))$('helloTitle').textContent='¡Hola, '+name+'!'};
window.editInstitution=function(){const now=localStorage.getItem('profego-institution')||'Mi institución',v=prompt('Nombre de la institución:',now);if(v&&v.trim()){localStorage.setItem('profego-institution',v.trim());applyProfile();toast('Institución actualizada')}};
const oldShow=window.show;window.show=function(id,b){if(oldShow)oldShow(id,b);if(id==='resources')renderResources();if(id==='activities')renderActivities()};
function init(){addStyle();patchNav();patchTop();patchPages();applyProfile();renderResources();const country=$('country');if(country){country.value=localStorage.getItem('profego-country')||'Uruguay';country.onchange=()=>{localStorage.setItem('profego-country',country.value);if($('countryTop'))$('countryTop').textContent=country.value;toast('País actualizado')}}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,0));else setTimeout(init,0);
})();