(()=>{
const CLIENT_ID='534108409799-7udi863se2enjcito8innohocmsktmv7.apps.googleusercontent.com';
function greeting(){const n=(localStorage.getItem('profego-name')||'').trim();const h=document.getElementById('hello');if(h)h.textContent=n?`¡Hola, ${n}!`:'¡Hola!'}
function askNameOnce(){if((localStorage.getItem('profego-name')||'').trim()){greeting();return}if(document.getElementById('profegoWelcome'))return;const o=document.createElement('div');o.id='profegoWelcome';o.style.cssText='position:fixed;inset:0;z-index:9999;background:#09284bb8;display:flex;align-items:center;justify-content:center;padding:20px;backdrop-filter:blur(5px)';o.innerHTML=`<div style="width:min(430px,94vw);background:var(--card);color:var(--ink);border:1px solid var(--line);border-radius:26px;padding:28px;box-shadow:0 25px 70px #0004"><div style="font-size:38px">🏃</div><h2 style="margin:8px 0">¡Bienvenido a ProfeGo!</h2><p class="muted">¿Cómo te llamás? Te vamos a recordar en este dispositivo.</p><input id="welcomeName" autocomplete="name" placeholder="Tu nombre" style="width:100%;border:1px solid var(--line);border-radius:12px;padding:13px;background:var(--card);color:var(--ink);margin:8px 0 12px"><button id="welcomeSave" class="primary" style="width:100%">Continuar</button></div>`;document.body.appendChild(o);const i=document.getElementById('welcomeName');const done=()=>{const n=i.value.trim();if(!n)return i.focus();localStorage.setItem('profego-name',n);const p=document.getElementById('profileName');if(p)p.value=n;greeting();o.remove()};document.getElementById('welcomeSave').onclick=done;i.addEventListener('keydown',e=>{if(e.key==='Enter')done()});setTimeout(()=>i.focus(),100)}
function cleanLegacyDrive(){const settings=document.getElementById('settings');if(!settings)return;settings.querySelectorAll('.card').forEach(card=>{if(card.id==='driveConnectCard')return;const txt=card.textContent||'';if(txt.includes('URL de carpeta de Drive')||txt.includes('Guardar referencia'))card.style.display='none'})}
function driveCard(){const settings=document.getElementById('settings');const grid=settings?.querySelector('.settings-grid');if(!grid)return;cleanLegacyDrive();let c=document.getElementById('driveConnectCard');if(!c){c=document.createElement('div');c.id='driveConnectCard';c.className='card';c.innerHTML=`<h3>Google Drive</h3><p class="muted">Elegí tu cuenta de Google una sola vez. Después ProfeGo podrá guardar tus planificaciones en tu Drive.</p><div class="toolbar"><button class="primary" id="driveConnectBtn">Conectar con Google Drive</button></div><div id="driveConnectStatus" class="status"></div>`;grid.appendChild(c)}localStorage.setItem('profego-google-client-id',CLIENT_ID);const btn=document.getElementById('driveConnectBtn');if(btn)btn.onclick=()=>connectDrive()}
function loadGIS(){return new Promise((resolve,reject)=>{if(window.google?.accounts?.oauth2)return resolve();let s=document.querySelector('script[data-profego-gis]');if(s){s.addEventListener('load',resolve,{once:true});s.addEventListener('error',reject,{once:true});return}s=document.createElement('script');s.src='https://accounts.google.com/gsi/client';s.async=true;s.defer=true;s.dataset.profegoGis='1';s.onload=resolve;s.onerror=reject;document.head.appendChild(s)})}
function status(msg,err=false){const s=document.getElementById('driveConnectStatus');if(!s)return;s.textContent=msg;s.style.background=err?'#fff0f0':'#e9fff4';s.style.color=err?'#b42318':'#08794b';s.classList.add('show')}
async function connectDrive(){status('Abriendo Google…');try{await loadGIS();if(typeof window.connectGoogleDrive==='function'){window.connectGoogleDrive();return}status('La conexión de Drive no terminó de cargar. Actualizá la página.',true)}catch(e){status('No se pudo cargar el inicio de sesión de Google.',true)}}
function init(){greeting();askNameOnce();driveCard()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,150));else setTimeout(init,150);
})();