(()=>{
const CLIENT_ID='534108409799-7udi863se2enjcito8innohocmsktmv7.apps.googleusercontent.com';
function greeting(){const n=(localStorage.getItem('profego-name')||'').trim();const h=document.getElementById('hello');if(h)h.textContent=n?`¡Hola, ${n}!`:'¡Hola!'}
function askNameOnce(){if(!localStorage.getItem('profego-active-user'))return;if((localStorage.getItem('profego-name')||'').trim()){greeting();return}let u=null;try{u=JSON.parse(localStorage.getItem('profego-active-user')||'null')}catch(e){};if(u?.given_name||u?.name){localStorage.setItem('profego-name',u.given_name||u.name);greeting();return}}
function cleanLegacyDrive(){const settings=document.getElementById('settings');if(!settings)return;settings.querySelectorAll('.card').forEach(card=>{if(card.id==='driveConnectCard')return;const txt=card.textContent||'';if(txt.includes('URL de carpeta de Drive')||txt.includes('Guardar referencia'))card.style.display='none'})}
function driveCard(){const settings=document.getElementById('settings');const grid=settings?.querySelector('.settings-grid');if(!grid)return;cleanLegacyDrive();let c=document.getElementById('driveConnectCard');if(!c){c=document.createElement('div');c.id='driveConnectCard';c.className='card';c.innerHTML=`<h3>Google Drive</h3><p class="muted">Tu cuenta de Google permite guardar y sincronizar tus planificaciones en tu propio Drive.</p><input id="googleClientId" type="hidden" value="${CLIENT_ID}"><div class="toolbar"><button class="primary" id="driveConnectBtn">Conectar con Google Drive</button></div><div id="driveConnectStatus" class="status"></div>`;grid.appendChild(c)}else{let inp=document.getElementById('googleClientId');if(!inp){inp=document.createElement('input');inp.id='googleClientId';inp.type='hidden';inp.value=CLIENT_ID;c.appendChild(inp)}else inp.value=CLIENT_ID}localStorage.setItem('profego-google-client-id',CLIENT_ID);const btn=document.getElementById('driveConnectBtn')||c.querySelector('button[onclick*="connectGoogleDrive"]');if(btn){btn.id='driveConnectBtn';btn.textContent='Conectar con Google Drive';btn.onclick=()=>connectDrive()}}
function loadGIS(){return new Promise((resolve,reject)=>{if(window.google?.accounts?.oauth2)return resolve();let s=document.querySelector('script[data-profego-gis]');if(s){if(window.google?.accounts?.oauth2)return resolve();s.addEventListener('load',resolve,{once:true});s.addEventListener('error',reject,{once:true});return}s=document.createElement('script');s.src='https://accounts.google.com/gsi/client';s.async=true;s.defer=true;s.dataset.profegoGis='1';s.onload=resolve;s.onerror=reject;document.head.appendChild(s)})}
function status(msg,err=false){const s=document.getElementById('driveConnectStatus');if(!s)return;s.textContent=msg;s.style.background=err?'#fff0f0':'#e9fff4';s.style.color=err?'#b42318':'#08794b';s.classList.add('show')}
function waitForConnector(ms=6000){return new Promise((resolve,reject)=>{const start=Date.now();const tick=()=>{if(typeof window.connectGoogleDrive==='function')return resolve(window.connectGoogleDrive);if(Date.now()-start>=ms)return reject(new Error('connector_timeout'));setTimeout(tick,120)};tick()})}
async function connectDrive(){status('Abriendo Google…');try{localStorage.setItem('profego-google-client-id',CLIENT_ID);const inp=document.getElementById('googleClientId');if(inp)inp.value=CLIENT_ID;await loadGIS();const connector=await waitForConnector();connector();}catch(e){console.error(e);status('No se pudo iniciar Google Drive. Recargá ProfeGo y probá otra vez.',true)}}
function init(){greeting();askNameOnce();driveCard()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,150));else setTimeout(init,150);
})();