(()=>{
const TODAY_PAGE_ID='today';
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function localKey(d=new Date()){const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`}
function dateKey(v){if(!v)return '';if(v instanceof Date)return localKey(v);const s=String(v);const iso=s.match(/^(\d{4})-(\d{2})-(\d{2})/);if(iso)return `${iso[1]}-${iso[2]}-${iso[3]}`;const uy=s.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/);if(uy)return `${uy[3]}-${String(uy[2]).padStart(2,'0')}-${String(uy[1]).padStart(2,'0')}`;const d=new Date(s);return isNaN(d)?'':localKey(d)}
function plans(){try{return JSON.parse(localStorage.getItem('profego-plans')||'[]')}catch(e){return []}}
function acts(cl){return cl?.activities||cl?.games||[]}
function activityHtml(a,i){const name=Array.isArray(a)?a[0]:(a.name||a.title||`Juego ${i+1}`),desc=Array.isArray(a)?a[1]:(a.desc||a.description||'');return `<div class="pg-today-game"><div class="pg-today-num">${i+1}</div><div><b>${esc(name)}</b>${desc?`<p>${esc(desc)}</p>`:''}</div></div>`}
function matchesToday(){const key=localKey(),out=[];plans().forEach((p,pi)=>(p.classes||[]).forEach((cl,ci)=>{if(dateKey(cl.date||cl.period)===key)out.push({p,cl,pi,ci})}));return out}
function render(){const host=document.getElementById('todayContent');if(!host)return;const today=new Date(),found=matchesToday();const date=today.toLocaleDateString('es-UY',{weekday:'long',day:'numeric',month:'long'});if(!found.length){host.innerHTML=`<div class="card pg-today-empty"><div class="pg-today-calendar">📅</div><h3>Hoy, ${esc(date)}</h3><p>No hay ninguna clase guardada con la fecha de hoy.</p><p class="muted">Cuando una clase de una planificación tenga esta fecha, va a aparecer automáticamente acá.</p><button class="primary" onclick="showById('plans',1)">Ver mis planificaciones</button></div>`;return}host.innerHTML=`<div class="pg-today-date">Hoy · ${esc(date)}</div>`+found.map(({p,cl,ci})=>`<section class="card pg-today-card"><div class="pg-today-head"><div><small>${esc(p.institution||'Institución')} · ${esc(p.group||'Grupo')}</small><h2>Clase ${ci+1}</h2><p>${esc(p.content||p.name||'Planificación')}</p></div><span class="pg-today-badge">HOY</span></div>${cl.goal||p.goal?`<div class="pg-today-goal"><b>Meta de aprendizaje</b><p>${esc(cl.goal||p.goal)}</p></div>`:''}<div class="pg-today-games">${acts(cl).map(activityHtml).join('')||'<p class="muted">Esta clase todavía no tiene juegos cargados.</p>'}</div></section>`).join('')}
function showToday(btn){if(typeof window.show==='function')window.show(TODAY_PAGE_ID,btn);else{document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));document.getElementById(TODAY_PAGE_ID)?.classList.add('active')}render()}
window.showToday=showToday;
function install(){const main=document.querySelector('main.main');const nav=document.querySelector('nav.side');if(!main||!nav)return false;if(!document.getElementById(TODAY_PAGE_ID)){const section=document.createElement('section');section.id=TODAY_PAGE_ID;section.className='page';section.innerHTML='<h2>Hoy</h2><div id="todayContent"></div>';const home=document.getElementById('home');home?.after(section)}if(!document.getElementById('todayNav')){const b=document.createElement('button');b.id='todayNav';b.title='Hoy';b.innerHTML='<svg viewBox="0 0 24 24"><rect x="4" y="5" width="16" height="15" rx="2"/><path d="M8 3v4M16 3v4M4 10h16"/><circle cx="12" cy="15" r="2"/></svg><span>Hoy</span>';b.style.background='linear-gradient(180deg,#5f8cff,#4469dc)';b.onclick=()=>showToday(b);const first=nav.querySelector('button');first?.after(b)}if(!document.getElementById('pgTodayStyle')){const st=document.createElement('style');st.id='pgTodayStyle';st.textContent=`.pg-today-date{font-weight:900;font-size:14px;margin:0 0 12px;color:var(--muted)}.pg-today-card{margin-bottom:14px}.pg-today-head{display:flex;justify-content:space-between;gap:14px;align-items:flex-start;border-bottom:1px solid var(--line);padding-bottom:12px}.pg-today-head h2{margin:3px 0 2px;font-size:26px}.pg-today-head p{margin:0;color:var(--muted)}.pg-today-head small{color:var(--muted)}.pg-today-badge{background:#1677ff;color:white;border-radius:999px;padding:7px 11px;font-size:11px;font-weight:900}.pg-today-goal{background:linear-gradient(90deg,#edf5ff,#f0fff8);border:1px solid var(--line);border-radius:14px;padding:12px;margin:14px 0}.dark .pg-today-goal{background:var(--soft)}.pg-today-goal p{margin:5px 0 0;line-height:1.45}.pg-today-games{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.pg-today-game{border:1px solid var(--line);border-radius:14px;padding:12px;display:grid;grid-template-columns:34px 1fr;gap:9px;background:var(--card)}.pg-today-num{width:30px;height:30px;border-radius:50%;display:grid;place-items:center;background:#1677ff;color:white;font-weight:900}.pg-today-game p{margin:5px 0 0;color:var(--muted);font-size:12px;line-height:1.4}.pg-today-empty{text-align:center;padding:34px}.pg-today-calendar{font-size:50px}.pg-today-empty h3{margin:8px 0}.pg-today-empty p{margin:6px auto;max-width:560px}.pg-today-empty button{margin-top:14px}@media(max-width:760px){.pg-today-games{grid-template-columns:1fr}.pg-today-head h2{font-size:22px}}`;document.head.appendChild(st)}render();return true}
let n=0;const t=setInterval(()=>{n++;if(install()||n>40)clearInterval(t)},100);window.addEventListener('storage',render);
})();